### ISSUE TITLE
quickstart guide 

### ISSUE THREAD

**Issue by zengqhb** [Activiti/activiti-7-developers-guide#29]
when I Starting a process using startProcess or startProcessWithVariables endpoints in rb-my-app folder, it response 404 not Found:
{
    "timestamp": "2018-08-29T10:28:02.078+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/rb-my-app/v1/process-instances"
}

**Comment by salaboy** [comment]
closing due inactivity
