### ISSUE TITLE
which gitbook version is used to build the book?

### ISSUE THREAD

**Issue by zhangpy** [Activiti/activiti-7-developers-guide#45]
I tried version 2.6.9, 3.2.3 and 4.0.0-alpha6 but failed.
```
gitbook -v 2.6.9 build
Error loading version latest: ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:27:26
    at Object.<anonymous> (~/.gitbook/versions/2.6.9/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```
```
gitbook -v 3.2.3 build / gitbook -v 4.0.0-alpha.6 build

error: error while generating page "getting-started/getting-started-activiti-cloud/README.md": 

Template render error: (activiti-7-developers-guide/getting-started/getting-started-activiti-cloud/README.md) [Line 75, Column 2]
  unknown block tag: hint
```
What is the correct gitbook version to build? thanks.

**Comment by mteodori** [comment]
the gitbook service is building we don't have any explicit build, I wasn't aware it was possible to build locally which is good to know, I would say you should search for the latest version or the one the service is using and then we can add this information to the README maybe

**Comment by mteodori** [comment]
from what I can read here the CLI tool is not supported anymore since a year ago at least
https://github.com/GitbookIO/gitbook
so I will be closing this issue

**Comment by codemedici** [comment]
Well then if it is not supported how am I supposed to publish my documentation? Thank you!
