### ISSUE TITLE
Visit the modeling application and prompt unknown error happened during the loading of projects？

### ISSUE THREAD

**Issue by linkai0001** [Activiti/activiti-7-developers-guide#51]
hello, Visit the modeling application and prompt unknown error happened during the loading of projects？
![image](https://user-images.githubusercontent.com/24260681/68475114-2dffa280-0262-11ea-9fb3-a3513884bf6f.png)
![image](https://user-images.githubusercontent.com/24260681/68476117-d7e02e80-0264-11ea-8d91-8bba47fa822a.png)
There seems to be more /modeling-service address mapping?

**Comment by mteodori** [comment]
thank you for reporting, the double /modeling-service in the URL has now been fixed and will go to M6
